### ISSUE TITLE
Plugin Will Not Run just come up with error 

### ISSUE THREAD

**Issue by nickyf114** [luizoti/script.library.integration.tool#41]
install the plugin try to run it on my laptop runing windows 11 says error as soon as you try to run it 
 so i went to my raspberry pi 4 libreelec  installed the plugin and it installed fine go to run the addon and error on this to  
my laptop and pi 4 was runing kodi 19.4 as well  thanks from nick

**Comment by MrCoolAndroid** [comment]
I have the same error on a CoreELEC device with Kodi Matrix, i can't even set it up because it just crashes when trying to open it, i can send a log if needed

**Comment by hartontw** [comment]
Hardware: ```Raspberry Pi 4```
LibreELEC: ``10.0.4``
KODI: ``Matrix 19.5``
Addon: `` v0.8.34`` 

``` 
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                 Error Type: <class 'ImportError'>
                 Error Contents: cannot import name 'mkdir' from 'resources.lib.filesystem' (/storage/.kodi/addons/script.library.integration.tool/resources/lib/filesystem.py)
                 Traceback (most recent call last):
                   File "/storage/.kodi/addons/script.library.integration.tool/service.py", line 14, in <module>
                     from resources.lib.menus.main import MainMenu
                   File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/menus/main.py", line 16, in <module>
                     from resources.lib.menus.movie.managed import ManagedMoviesMenu
                   File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/menus/movie/managed.py", line 11, in <module>
                     from resources.lib.content.movie.managed import ManagedMovie
                   File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/content/movie/managed.py", line 7, in <module>
                     from resources.lib.content.movie.movie import MovieFileManager
                   File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/content/movie/movie.py", line 15, in <module>
                     from resources.lib.filesystem import join, mkdir, removedir
                 ImportError: cannot import name 'mkdir' from 'resources.lib.filesystem' (/storage/.kodi/addons/script.library.integration.tool/resources/lib/filesystem.py)
                 -->End of Python script error report<--
```
