### ISSUE TITLE
Matrix: `Error Contents: No module named 'resources.lib.items.contentmanager'`

### ISSUE THREAD

**Issue by shtrom** [luizoti/script.library.integration.tool#42]
**Describe the bug**
The Matrix branch no longer has `resources.lib.items.contentmanager` https://github.com/luizoti/script.library.integration.tool/commit/c92a7b198170d1c1c3b1036267c018fea2a1a73e, but it is still referenced by other modules https://github.com/luizoti/script.library.integration.tool/blob/Matrix/resources/lib/__init__.py#L6

**To Reproduce**
1. Go to any plugin (in Matrix with the Matrix branch)
2. Click on 'Sync directly do library'
3. See error notification

**Expected behavior**

Selected entry is synced.

**Desktop (please complete the following information):**
 - OS: LibreElec / RPi4
 - Kodi Version 19.XX

**Kodi log**
```
2022-08-03 23:19:38.452 T:1902    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'resources.lib.items.contentmanager'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.library.integration.tool/context.py", line 16, in <module>
                                                       from resources.lib.database import Database
                                                     File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/__init__.py", line 6, in <module>
                                                       from resources.lib.items.contentmanager import ContentManagerMovie, ContentManagerShow
                                                   ModuleNotFoundError: No module named 'resources.lib.items.contentmanager'
                                                   -->End of Python script error report<--
```

**Comment by luizoti** [comment]
I'm rewriting a lot of things in LIT, but I think, I think because it's been a while since I did that, the [melies ](https://github.com/luizoti/repository.melies) repository version is ok, I had to pause the work on lit for lack of time.
